/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package downloader;

import java.awt.Rectangle;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rajib
 */
public class DownloadStatus extends javax.swing.JFrame {

    /**
     * Creates new form DownloadStatus
     */
    DefaultTableModel dm;
    public DownloadStatus() {
        initComponents();
        setLocationRelativeTo(null);
        initializeTable();
        
        AddNewRow("www.google.com", "Processing");
        AddNewRow("www.FaceBook.com", "Processing");

    }
    private void initializeTable()
    {
        dm = new DefaultTableModel(0, 0);
        String header[] = new String[]{"URL", "Status"};
        dm.setColumnIdentifiers(header);
        downloadTable.setModel(dm);
        
        Rectangle r = this.getBounds();
        int h = r.height;
        int w = r.width;
        System.out.println("");
        downloadTable.getColumnModel().getColumn(0).setPreferredWidth(80 * w / 100);
        downloadTable.getColumnModel().getColumn(1).setPreferredWidth(20 * w / 100);
        
        
    }
    
    public void AddNewRow(String fileUrl, String status)
    {
        Vector<Object> data = new Vector<Object>();
        data.add(fileUrl);
        data.add(status);
        
        dm.addRow(data);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressBar = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        downloadTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        downloadTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "URL", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(downloadTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable downloadTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
